import { nanoid } from "nanoid";

const TRIPS = [
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    date: "17 ноя, пт",
    image: `images/image1.png`,
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    date: "17 ноя, пт",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    date: "17 ноя, пт",
    image: `images/image1.png`,
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    date: "17 ноя, пт",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Газель фермер",
    price: 500,
    location: "Екатеринбург",
    cargoType: [
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/image1.png`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Камаз",
    price: 700,
    location: "Екатеринбург",
    cargoType: [
      "Люди",
      "Мебель",
      "Личные вещи",
      "Стройматериалы",
      "Техника и оборудование",
      "Комлектующие для пк",
      "Одежда",
    ],
    image: `images/Kamaz.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Bmw",
    price: 1500,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Bmw.jpg`,
    date: "17 ноя, пт",
  },
  {
    id: nanoid(),
    title: "Camry",
    price: 1200,
    location: "Екатеринбург",
    cargoType: ["Люди", "Личные вещи", "Одежда"],
    image: `images/Camry.jpg`,
    date: "17 ноя, пт",
  },
];

function fetchGetTrips(page?: number, limit?: number) {
  if (page && limit) {
    const currentTrips = TRIPS.slice((page - 1) * limit, page * limit);
    if (currentTrips.length === 0) {
      return new Promise((res, rej) => {
        setTimeout(
          () => rej({ errorMessage: "Поездок больше не найдено", status: 404 }),
          250
        );
      });
    }

    return new Promise((res) => {
      setTimeout(() => res(currentTrips), 250);
    });
  }
  const currentTrips = TRIPS.slice(0, 10);

  return new Promise((res) => {
    setTimeout(() => res(currentTrips), 250);
  });
}

export { fetchGetTrips };
